version: '3.8'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      ROARR_LOG: true
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - voting_db:/var/lib/postgresql/data
      - ./database/db_init.sql:/docker-entrypoint-initdb.d/init.sql

  db_test:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./database/db_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  voting_db:
